backend:
  name: test-repo
  local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "products"
    label: "Prodotti"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Descrizione", name: "description", widget: "text" }
      - { label: "Prezzo", name: "price", widget: "number" }
      - { label: "Immagine", name: "image", widget: "image" }
